name: Continuous Integration
on: 
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          RELEASE_BRANCHES: main,master
          DEFAULT_BUMP: patch
          WITH_V: true